export const notes = [
  {
    id: "12345",
    timestamp: "Sun, 27 Aug 2023 23:43:55 GMT",
    blocks: [
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "9adb5",
        text: "Lorem ipsum",
        type: "header-one",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [
          {
            offset: 0,
            length: 11,
            style: "BOLD",
          },
          {
            offset: 27,
            length: 11,
            style: "ITALIC",
          },
          {
            offset: 39,
            length: 16,
            style: "UNDERLINE",
          },
        ],
        key: "3eesq",
        text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ",
        type: "unstyled",
      },
    ],
  },

  {
    id: "12339582",
    timestamp: "Sat, 26 Aug 2023 22:43:55 GMT",
    blocks: [
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "3eess",
        text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        type: "unstyled",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "4geah",
        text: "",
        type: "unstyled",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "a63hd",
        text: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "gg4aj",
        text: "",
        type: "unstyled",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "7eala",
        text: "Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.",
        type: "unstyled",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "gaga3",
        text: "",
        type: "unstyled",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 6, style: "CODEBLOCK" }],
        key: "code1",
        text: "body {",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 14, style: "CODEBLOCK" }],
        key: "code2",
        text: "display: flex;",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 24, style: "CODEBLOCK" }],
        key: "code3",
        text: "justify-content: center;",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 20, style: "CODEBLOCK" }],
        key: "code4",
        text: "align-items: center;",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 18, style: "CODEBLOCK" }],
        key: "code5",
        text: "margin: 2rem auto;",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 18, style: "CODEBLOCK" }],
        key: "code6",
        text: "background: #ddd;",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [{ offset: 0, length: 1, style: "CODEBLOCK" }],
        key: "code7",
        text: "}",
        type: "blockQuote",
      },
      {
        data: {},
        depth: 0,
        entityRanges: [],
        inlineStyleRanges: [],
        key: "gafa3",
        text: "",
        type: "unstyled",
      },
    ],
  },
];
